# Generated by Django 4.1.5 on 2023-03-12 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_content_date_alter_profileimg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 12, 20, 55, 8, 191260)),
        ),
    ]
