# Generated by Django 4.1.5 on 2023-03-14 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_content_date_alter_profileimg_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=10000)),
                ('content_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='content',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 14, 16, 18, 29, 760955)),
        ),
        migrations.AlterField(
            model_name='profileimg',
            name='image',
            field=models.ImageField(default='default-profile.jpg', upload_to='images/'),
        ),
    ]
