# Generated by Django 4.1.5 on 2023-03-14 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_comment_alter_content_date_alter_profileimg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 14, 16, 22, 25, 77039)),
        ),
        migrations.AlterField(
            model_name='content',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 14, 16, 22, 24, 998800)),
        ),
    ]
